[package]
name = "http-spi-bridge"
version = "0.1.0"
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.52"
axum = "0.4.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
spidev = "0.5.1"
structopt = "0.3.26"
tokio = { version = "1.16.1", features = ["fs", "io-util", "macros", "process", "rt-multi-thread"] }
tracing = "0.1.30"
tracing-subscriber = { version = "0.3.8", features = ["env-filter"] }

[profile.release]
lto = "fat"
codegen-units = 1
