[package]
name = "http-spi-bridge"
version = "0.1.0"
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.48"
axum = "0.4.3"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
spidev = "0.5.1"
structopt = "0.3.25"
tokio = { version = "1.15.0", features = ["fs", "io-util", "macros", "process", "rt-multi-thread"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }

[profile.release]
lto = "fat"
codegen-units = 1
