[package]
name = "http-spi-bridge"
version = "0.1.0"
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.41"
libc = "0.2.97"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
spidev = "0.4.1"
structopt = "0.3.21"
tokio = { version = "1.7.1", features = ["full"] }
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
warp = "0.3.1"

[profile.release]
lto = "fat"
