[package]
name = "http-spi-bridge"
version = "0.1.0"
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.42"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
spidev = "0.4.1"
structopt = "0.3.21"
tokio = { version = "1.7.1", features = ["process"] }
tracing = "0.1.26"
tracing-subscriber = "0.2.19"

[profile.release]
lto = "fat"
codegen-units = 1
