name: publish
on:
  workflow_dispatch:
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: nix-community
      - name: nix-build
        run: |
          nix build -L
          mkdir -p ~/result
          cp -v ./result/bin/http-spi-bridge ~/result
      - uses: actions/upload-artifact@v3
        with:
          name: http-spi-bridge
          path: ~/result/http-spi-bridge
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [ nix-build ]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/download-artifact@v3
        with:
          name: http-spi-bridge
      - uses: mathieudutour/github-tag-action@v6.1
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.tag.outputs.changelog }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: ./http-spi-bridge
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
